### ISSUE TITLE
Where are 'sim_model.pt' and 'pretrain_model.pt'  in rl-sim from?

### ISSUE THREAD

**Issue by keith-nlp** [zdou0830/crosslingual_summarization_semantic#1]
Hello! 

According to `./rl-sim/train.json`, it requires **"sim_model_file"** and **"train_from"**. I would like to know if they are model checkpoints from `word-level-supervised `and `sent-level-supervised`. Could you please confirm if I understand this collectedly: 

-  sim_model_file: `path/to/word-level-supervised/model-checkpoint`
- train_from: `path/to/sent-level-supervised/model-checkpoint`

Thanks!

**Comment by zdou0830** [comment]
Hello!

The sim_model_file is model from https://github.com/jwieting/simple-and-effective-paraphrastic-similarity, the train_from is model from word-level-supervised or sent-level-supervised.
